skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "5MyQPKV12rGp2c3ce3qeA8yk2BdDhVJvBJt6TePeRe5F"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
